Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Canapele"] = { -- apa_mp_h_stn_foot_stool_02
    { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Canapea veche" },
    { ["object"] = "apa_mp_h_stn_sofa2seat_02", ["price"] = 300, ["name"] = "Canapea Alba" },
    { ["object"] = "apa_mp_h_05_sofa", ["price"] = 500, ["name"] = "Canapea Neagra Mare" },
    { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 2000, ["name"] = "Canapea Alba-Rosie" },
    { ["object"] = "sum_mp_h_yacht_sofa_01", ["price"] = 2500, ["name"] = "Canapea Yacht" },
    { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 250, ["name"] = "Canapea de zi neagra" }, -- gr_prop_gr_bench_01b
    { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 250, ["name"] = "Canapea de zi crem" },
    { ["object"] = "v_ilev_m_sofa", ["price"] = 700, ["name"] = "Canapea Alba" },
    { ["object"] = "v_res_tre_sofa_s", ["price"] = 700, ["name"] = "Canapea Albastra" },
    { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 700, ["name"] = "Canapea coltar 1" },
    { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 700, ["name"] = "Canapea coltar 2" },
    { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 700, ["name"] = "Canapea coltar 3" },
    { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 700, ["name"] = "Canapea coltar 4" },
    { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 700, ["name"] = "Canapea coltar 5" },
    { ["object"] = "apa_mp_h_stn_sofacorn_09", ["price"] = 700, ["name"] = "Canapea coltar 6" },
    { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 700, ["name"] = "Canapea coltar 7" },
    { ["object"] = "gr_dlc_gr_yacht_props_seat_01", ["price"] = 250, ["name"] = "Fotoliu Gri" },
    { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Fotoliu vechi" },
    { ["object"] = "apa_mp_h_stn_chairarm_01", ["price"] = 300, ["name"] = "Fotoliu Maro" },
    { ["object"] = "apa_mp_h_stn_chairstrip_01", ["price"] = 250, ["name"] = "Fotoliu Portocaliu" },
    { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "Suport picioare" },
    { ["object"] = "gr_dlc_gr_yacht_props_lounger", ["price"] = 250, ["name"] = "Sezlong" },
	{ ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 700, ["name"] = "Pat de zi 1" },
	{ ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 700, ["name"] = "Pat de zi 2" },
  },
  ['Paturi'] = {
    { ["object"] = "p_lestersbed_s", ["price"] = 300, ["name"] = "Pat 1" },
    { ["object"] = "p_mbbed_s", ["price"] = 300, ["name"] = "Pat 2" },
    { ["object"] = "p_v_res_tt_bed_s", ["price"] = 300, ["name"] = "Pat 3" },
    { ["object"] = "v_res_msonbed_s", ["price"] = 300, ["name"] = "Pat 4" }, -- v_16_bdr_mesh_bed
    { ["object"] = "v_16_bdr_mesh_bed", ["price"] = 300, ["name"] = "Pat 5" },
    { ["object"] = "ba_daybed1", ["price"] = 300, ["name"] = "Pat 6" },
  },
  ["Electrocasnice"] = {
    { ["object"] = "prop_arcade_01", ["price"] = 300, ["name"] = "Arcade bar" },
    { ["object"] = "apa_mp_h_acc_phone_01", ["price"] = 300, ["name"] = "Telefon fix" },
    { ["object"] = "prop_fan_01", ["price"] = 300, ["name"] = "Ventilator 1" },
    { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Ventilator 2" },
    { ["object"] = "v_ilev_lest_bigscreen", ["price"] = 300, ["name"] = "Ecran Proiector" },
    { ["object"] = "ex_prop_monitor_01_ex", ["price"] = 300, ["name"] = "iMac" },
    { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
    { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
    { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Laptop" },
    { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },
    { ["object"] = "prop_tv_flat_03", ["price"] = 500, ["name"] = "Monitor HD" },
    { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "Plasma1" },
    { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "Plasma 2" },
    { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "Home Cinema" },
    { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "Computer Keyboard" },
    { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Coffeemachine" },
    { ["object"] = "hei_heist_str_avunitl_03", ["price"] = 1500, ["name"] = "Home Cinema" },
    { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 2000, ["name"] = "Home Cinema 2" },
    { ["object"] = "prop_controller_01", ["price"] = 300, ["name"] = "Joystick" },
    { ["object"] = "prop_console_01", ["price"] = 1000, ["name"] = "Consola" },
    { ["object"] = "bkr_prop_fakeid_desklamp_01a", ["price"] = 1000, ["name"] = "Lampa Birou" },
    { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 1500, ["name"] = "TV + Mobila" }, -- bkr_prop_fakeid_desklamp_01a
    { ["object"] = "prop_speaker_01", ["price"] = 100, ["name"] = "Boombox 1" },
    { ["object"] = "prop_speaker_02", ["price"] = 100, ["name"] = "Boombox 2" },
    { ["object"] = "prop_speaker_03", ["price"] = 100, ["name"] = "Boombox 3" },
    { ["object"] = "prop_speaker_04", ["price"] = 100, ["name"] = "Boombox 4" },
    { ["object"] = "prop_speaker_05", ["price"] = 100, ["name"] = "Boombox 5" },
    { ["object"] = "prop_speaker_06", ["price"] = 100, ["name"] = "Boombox 6" },
    { ["object"] = "prop_speaker_07", ["price"] = 100, ["name"] = "Boombox 7" },
    { ["object"] = "prop_speaker_08", ["price"] = 100, ["name"] = "Boombox 8" },
    { ["object"] = "prop_boombox_01", ["price"] = 250, ["name"] = "Boombox" },
  },
  ["Sala"] = {
    { ["object"] = "prop_freeweight_01", ["price"] = 750, ["name"] = "Gantere 1" },
    { ["object"] = "prop_freeweight_02", ["price"] = 750, ["name"] = "Gantere 2" },
    { ["object"] = "prop_weight_1_5k", ["price"] = 750, ["name"] = "Gantere 1.5KG" },
    { ["object"] = "prop_weight_2_5k", ["price"] = 750, ["name"] = "Gantere 2.5KG" },
    { ["object"] = "prop_weight_5k", ["price"] = 750, ["name"] = "Gantere 5KG" },
    { ["object"] = "prop_weight_10k", ["price"] = 750, ["name"] = "Gantere 10KG" },
    { ["object"] = "prop_weight_15k", ["price"] = 750, ["name"] = "Gantere 15KG" },
    { ["object"] = "prop_weight_20k", ["price"] = 750, ["name"] = "Gantere 20KG" },
    { ["object"] = "prop_weight_bench_02", ["price"] = 750, ["name"] = "Banca" },
    { ["object"] = "prop_weight_rack_01", ["price"] = 750, ["name"] = "Weight Rack 1" },
    { ["object"] = "prop_weight_rack_02", ["price"] = 750, ["name"] = "Weight Rack 2" },
    { ["object"] = "prop_weight_squat", ["price"] = 750, ["name"] = "Squat Rack" },
    { ["object"] = "prop_muscle_bench_01", ["price"] = 750, ["name"] = "Banca 1" },
    { ["object"] = "prop_muscle_bench_02", ["price"] = 750, ["name"] = "Banca 2" },
    { ["object"] = "prop_muscle_bench_03", ["price"] = 750, ["name"] = "Banca 3" },
    { ["object"] = "prop_muscle_bench_04", ["price"] = 750, ["name"] = "Banca 4" },
    { ["object"] = "prop_muscle_bench_05", ["price"] = 750, ["name"] = "Banca 5" },
    { ["object"] = "prop_muscle_bench_06", ["price"] = 750, ["name"] = "Banca 6" },
    { ["object"] = "prop_exer_bike_01", ["price"] = 750, ["name"] = "Bicicleta 1" },
    { ["object"] = "prop_exer_bike_mg", ["price"] = 750, ["name"] = "Bicicleta 2" },
    { ["object"] = "prop_exercisebike", ["price"] = 750, ["name"] = "Bicicleta 3" },
    { ["object"] = "apa_p_apdlc_treadmill_s", ["price"] = 750, ["name"] = "Banda de alergat" },
    { ["object"] = "v_ilev_exball_blue", ["price"] = 750, ["name"] = "Minge Albastra" },
    { ["object"] = "v_ilev_exball_grey", ["price"] = 750, ["name"] = "Minge Gri" },
    { ["object"] = "prop_rolled_yoga_mat", ["price"] = 750, ["name"] = "Covoras Strans" },
    { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Covoras 1" },
    { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Covoras 2" },
    { ["object"] = "p_yoga_mat_01_s", ["price"] = 750, ["name"] = "Covoras 3" },
    { ["object"] = "p_yoga_mat_02_s", ["price"] = 750, ["name"] = "Covoras 4" },
    { ["object"] = "p_yoga_mat_03_s", ["price"] = 750, ["name"] = "Covoras 5" },
    { ["object"] = "prop_yoga_mat_01", ["price"] = 750, ["name"] = "Covoras 6" },
    { ["object"] = "prop_yoga_mat_02", ["price"] = 750, ["name"] = "Covoras 7" },
    { ["object"] = "prop_yoga_mat_03", ["price"] = 750, ["name"] = "Covoras 8" },
    { ["object"] = "prop_barbell_01", ["price"] = 750, ["name"] = "Haltere 1" },
    { ["object"] = "prop_barbell_02", ["price"] = 750, ["name"] = "Haltere 2" },
    { ["object"] = "prop_barbell_10kg", ["price"] = 750, ["name"] = "Haltere 10KG" },
    { ["object"] = "prop_barbell_20kg", ["price"] = 750, ["name"] = "Haltere 20KG" },
    { ["object"] = "prop_barbell_30kg", ["price"] = 750, ["name"] = "Haltere 30KG" },
    { ["object"] = "prop_barbell_40kg", ["price"] = 750, ["name"] = "Haltere 40KG" },
    { ["object"] = "prop_barbell_50kg", ["price"] = 750, ["name"] = "Haltere 50KG" },
    { ["object"] = "prop_barbell_60kg", ["price"] = 750, ["name"] = "Haltere 60KG" },
    { ["object"] = "prop_barbell_80kg", ["price"] = 750, ["name"] = "Haltere 80KG" },
    { ["object"] = "prop_barbell_100kg", ["price"] = 750, ["name"] = "Haltere 100KG" },
  },
  ["Mese"] = {
    { ["object"] = "prop_table_02", ["price"] = 500, ["name"] = "Masa Rotunda 1" },
    { ["object"] = "prop_table_05", ["price"] = 500, ["name"] = "Masa Rotunda 2" },
    { ["object"] = "apa_mp_h_din_table_06", ["price"] = 500, ["name"] = "Masa Rotunda 3" }, -- ex_mp_h_din_table_06
    { ["object"] = "ex_mp_h_din_table_06", ["price"] = 500, ["name"] = "Masa Rotunda 4" },

    { ["object"] = "prop_table_01", ["price"] = 500, ["name"] = "Masa Normala 1" },
    { ["object"] = "prop_table_04", ["price"] = 500, ["name"] = "Masa Normala 2" },
    { ["object"] = "prop_table_06", ["price"] = 500, ["name"] = "Masa Normala 3" },
    { ["object"] = "prop_table_02", ["price"] = 500, ["name"] = "Masa Normala 4" },
    { ["object"] = "prop_table_03", ["price"] = 500, ["name"] = "Masa Normala 5" },
    { ["object"] = "hei_heist_din_table_06", ["price"] = 500, ["name"] = "Masa Normala 6" },

    { ["object"] = "prop_t_coffe_table", ["price"] = 750, ["name"] = "Masa de sticla 1" },
    { ["object"] = "bkr_prop_meth_table01a", ["price"] = 500, ["name"] = "Masa metamfetamina" },
    { ["object"] = "gr_prop_gr_bench_01a", ["price"] = 500, ["name"] = "Workbench 1" },
    { ["object"] = "gr_prop_gr_bench_01b", ["price"] = 500, ["name"] = "Workbench 2" },
    { ["object"] = "prop_table_02", ["price"] = 500, ["name"] = "Masa Rotunda" },
    { ["object"] = "apa_mp_h_tab_sidelrg_02", ["price"] = 500, ["name"] = "Masuta de cafea 1" }, 
    { ["object"] = "ex_mp_h_yacht_coffee_table_02", ["price"] = 500, ["name"] = "Masuta de cafea 2" },
    { ["object"] = "ex_mp_h_yacht_coffee_table_01", ["price"] = 500, ["name"] = "Masuta de cafea 3" }, 
    { ["object"] = "ex_mp_h_tab_coffee_08", ["price"] = 500, ["name"] = "Masuta de cafea 4" }, 
    { ["object"] = "ex_mp_h_tab_coffee_05", ["price"] = 500, ["name"] = "Masuta de cafea 5" }, 

    { ["object"] = "ex_mp_h_din_table_05", ["price"] = 500, ["name"] = "Birou 1" },  --apa_mp_h_str_sideboards_02
    { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 3000, ["name"] = "Birou 2" }, 
    { ["object"] = "xm_prop_base_staff_desk_02", ["price"] = 3000, ["name"] = "Birou 3" }, 
    { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 3000, ["name"] = "Birou 4" }, 
  },
  ['Scaune'] = {
    { ["object"] = "prop_chair_02", ["price"] = 250, ["name"] = "Scaun 1" },
    { ["object"] = "prop_chair_01b", ["price"] = 250, ["name"] = "Scaun 2" },
    { ["object"] = "prop_chair_04a", ["price"] = 250, ["name"] = "Scaun 3" },
    { ["object"] = "prop_chair_04b", ["price"] = 250, ["name"] = "Scaun 4" },
    { ["object"] = "prop_chair_06", ["price"] = 250, ["name"] = "Scaun 5" },
    { ["object"] = "prop_chair_07", ["price"] = 250, ["name"] = "Scaun 6" },
    { ["object"] = "prop_chair_09", ["price"] = 250, ["name"] = "Scaun 7" },
    { ["object"] = "prop_chateau_chair_01", ["price"] = 700, ["name"] = "Scaun 8" },
    { ["object"] = "prop_gc_chair02", ["price"] = 700, ["name"] = "Scaun 9" },
    { ["object"] = "v_ilev_chair02_ped", ["price"] = 250, ["name"] = "Scaun 10" },
    { ["object"] = "v_corp_cd_chair", ["price"] = 250, ["name"] = "Scaun 11" },
    { ["object"] = "v_corp_bk_chair3", ["price"] = 250, ["name"] = "Scaun 12" },
    { ["object"] = "prop_skid_chair_03", ["price"] = 250, ["name"] = "Scaun 13" },
    { ["object"] = "p_ilev_p_easychair_s", ["price"] = 250, ["name"] = "Scaun 14" },
    { ["object"] = "v_ilev_fh_dineeamesa", ["price"] = 250, ["name"] = "Scaun 15" },
    { ["object"] = "ex_mp_h_yacht_barstool_01", ["price"] = 250, ["name"] = "Scaun bar" },
    { ["object"] = "prop_cs_folding_chair_01", ["price"] = 250, ["name"] = "Scaun pliabil" },

    { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Scaun Regizor 1" },
    { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Scaun Regizor 2" },
    { ["object"] = "prop_cs_office_chair", ["price"] = 700, ["name"] = "Scaun birou 1" },
    { ["object"] = "p_clb_officechair_s", ["price"] = 700, ["name"] = "Scaun birou 2" },
    { ["object"] = "prop_off_chair_04_s", ["price"] = 700, ["name"] = "Scaun birou 3" },
    { ["object"] = "prop_off_chair_04", ["price"] = 700, ["name"] = "Scaun birou 4" },
    { ["object"] = "prop_off_chair_03", ["price"] = 700, ["name"] = "Scaun birou 5" },
    { ["object"] = "prop_off_chair_01", ["price"] = 700, ["name"] = "Scaun birou 6" },
    { ["object"] = "prop_off_chair_05", ["price"] = 700, ["name"] = "Scaun birou 7" },
    { ["object"] = "v_club_officechair", ["price"] = 700, ["name"] = "Scaun birou 8" },
    { ["object"] = "sm_prop_smug_offchair_01a", ["price"] = 250, ["name"] = "Scaun birou 9" },
    { ["object"] = "hei_prop_heist_off_chair", ["price"] = 250, ["name"] = "Scaun birou 10" },
    { ["object"] = "v_corp_offchair", ["price"] = 700, ["name"] = "Scaun birou 11" },

    { ["object"] = "apa_mp_h_din_chair_04", ["price"] = 250, ["name"] = "Scaun living 1" },
    { ["object"] = "apa_mp_h_din_chair_08", ["price"] = 250, ["name"] = "Scaun living 2" },
    { ["object"] = "apa_mp_h_din_chair_09", ["price"] = 250, ["name"] = "Scaun living 3" },
    { ["object"] = "apa_mp_h_din_chair_12", ["price"] = 250, ["name"] = "Scaun living 4" },

    { ["object"] = "prop_table_02_chr", ["price"] = 700, ["name"] = "Scaun masa 1" },
    { ["object"] = "prop_table_01_chr_a", ["price"] = 250, ["name"] = "Scaun masa 2" },
    { ["object"] = "prop_table_01_chr_b", ["price"] = 250, ["name"] = "Scaun masa 3" },
    { ["object"] = "prop_table_02_chr", ["price"] = 250, ["name"] = "Scaun masa 4" },
    { ["object"] = "prop_table_03_chr", ["price"] = 250, ["name"] = "Scaun masa 5" },
    { ["object"] = "prop_table_03b_chr", ["price"] = 250, ["name"] = "Scaun masa 6" },
    { ["object"] = "prop_table_04_chr", ["price"] = 250, ["name"] = "Scaun masa 7" },
    { ["object"] = "prop_table_05_chr", ["price"] = 250, ["name"] = "Scaun masa 8" },

    { ["object"] = "p_soloffchair_s", ["price"] = 700, ["name"] = "Scaun Lux 1" },
    { ["object"] = "prop_sol_chair", ["price"] = 700, ["name"] = "Scaun Lux 2" },

    { ["object"] = "prop_rock_chair_01", ["price"] = 700, ["name"] = "Scaun de batrani" },
    { ["object"] = "prop_torture_ch_01", ["price"] = 1000, ["name"] = "Scaun de tortura" },
    { ["object"] = "prop_wheelchair_01", ["price"] = 700, ["name"] = "Scaun cu rotile" },
    { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 250, ["name"] = "Taburete" },
  },
  ['Decoratiuni Perete'] = {
    { ["object"] = "prop_game_clock_01", ["price"] = 300, ["name"] = "Ceas Crown" },
    { ["object"] = "prop_game_clock_02", ["price"] = 300, ["name"] = "Ceas Kronos" },
    { ["object"] = "prop_id2_20_clock", ["price"] = 300, ["name"] = "Ceas Modern 1" },
    { ["object"] = "prop_sm_19_clock", ["price"] = 300, ["name"] = "Ceas Modern 2" },
    { ["object"] = "prop_v_5_bclock", ["price"] = 300, ["name"] = "Ceas Vintage" },
    { ["object"] = "prop_v_15_cars_clock", ["price"] = 300, ["name"] = "Ceas USA" },
    { ["object"] = "prop_sports_clock_01", ["price"] = 300, ["name"] = "Ceas Sport" },
  	{ ["object"] = "v_ilev_ra_doorsafe", ["price"] = 500, ["name"] = "Painting" },
  	{ ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Chalk Board" },
  	{ ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 300, ["name"] = "Wall Art 1" },
  	{ ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 300, ["name"] = "Wall Art 2" },
  	{ ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Wall Art 3" },
  	{ ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 300, ["name"] = "Wall Art 4" },
  	{ ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 300, ["name"] = "Wall Art 5" },
  	{ ["object"] = "hei_prop_hei_pic_hl_valkyrie", ["price"] = 300, ["name"] = "Valkyrie" },
  	{ ["object"] = "hei_prop_hei_pic_pb_bus", ["price"] = 300, ["name"] = "Prison Bus" },
    { ["object"] = "hei_prop_hei_pic_pb_plane", ["price"] = 300, ["name"] = "Plane" },
    { ["object"] = "hei_prop_hei_pic_pb_station", ["price"] = 300, ["name"] = "MRPD" },
    { ["object"] = "hei_prop_hei_pic_ps_bike", ["price"] = 300, ["name"] = "Lost MC" },
    { ["object"] = "hei_prop_hei_pic_ps_job", ["price"] = 300, ["name"] = "Pacific Standard" },
    { ["object"] = "hei_prop_heist_pic_05", ["price"] = 300, ["name"] = "Helicopter" },
    { ["object"] = "hei_prop_heist_pic_06", ["price"] = 300, ["name"] = "Plane" },
    { ["object"] = "hei_prop_heist_pic_10", ["price"] = 300, ["name"] = "Humane Labs" },
    { ["object"] = "hei_prop_heist_pic_12", ["price"] = 300, ["name"] = "Motorcycle" },
    { ["object"] = "hei_prop_heist_pic_13", ["price"] = 300, ["name"] = "Jetskis" },
    { ["object"] = "hei_prop_heist_pic_14", ["price"] = 300, ["name"] = "Water" },
    { ["object"] = "prop_j_heist_pic_04", ["price"] = 300, ["name"] = "Jewelry Store" },
    { ["object"] = "prop_j_heist_pic_03", ["price"] = 300, ["name"] = "Tunnel" },
    { ["object"] = "v_ilev_ra_doorsafe", ["price"] = 300, ["name"] = "Painting" },
    { ["object"] = "hei_heist_acc_artwalll_01", ["price"] = 300, ["name"] = "Painting 2" },
    { ["object"] = "hei_heist_acc_artwallm_01", ["price"] = 300, ["name"] = "Wall Art" },
    { ["object"] = "hei_heist_acc_artgolddisc_01", ["price"] = 300, ["name"] = "Gold Disc 1" },
    { ["object"] = "hei_heist_acc_artgolddisc_02", ["price"] = 300, ["name"] = "Gold Disc 2" },
    { ["object"] = "hei_heist_acc_artgolddisc_03", ["price"] = 300, ["name"] = "Gold Disc 3" },
    { ["object"] = "hei_heist_acc_artgolddisc_04", ["price"] = 300, ["name"] = "Gold Disc 4" },
	{ ["object"] = "prop_protest_sign_01", ["price"] = 300, ["name"] = "Protest Poster" },
	{ ["object"] = "prop_barrachneon", ["price"] = 300, ["name"] = "Neon Beer Sign 1" },
	{ ["object"] = "prop_beer_neon_02", ["price"] = 300, ["name"] = "Neon Beer Sign 2" },
	{ ["object"] = "prop_beer_neon_03", ["price"] = 300, ["name"] = "Neon Beer Sign 3" },
	{ ["object"] = "prop_beer_neon_04", ["price"] = 300, ["name"] = "Neon Beer Sign 4" },
	{ ["object"] = "prop_beerneon", ["price"] = 300, ["name"] = "Neon Beer Sign 5" },
	{ ["object"] = "prop_cherenneon", ["price"] = 300, ["name"] = "Neon Cherenkov Sign" },
	{ ["object"] = "prop_cockneon", ["price"] = 300, ["name"] = "Neon Cocktail Sign" },
	{ ["object"] = "prop_loggneon", ["price"] = 300, ["name"] = "Neon Logger Sign" },
	{ ["object"] = "prop_patriotneon", ["price"] = 300, ["name"] = "Neon Patriot Sign" },
	{ ["object"] = "prop_ragganeon", ["price"] = 300, ["name"] = "Neon Ragga Sign" },
  },
  ['Decoratiuni Interioare'] = {
    { ["object"] = "prop_acc_guitar_01", ["price"] = 1000, ["name"] = "Chitara" },
    { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "Chitara electrica 1" },
    { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "Chitara electrica 2" },
    { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "Chitara electrica 2" },
    { ["object"] = "apa_mp_h_acc_bottle_01", ["price"] = 700, ["name"] = "Sticla" },  
    { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 700, ["name"] = "Lumanari 1" }, 
    { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 50, ["name"] = "Lumanari 2" },
    { ["object"] = "apa_mp_h_acc_candles_05", ["price"] = 50, ["name"] = "Lumanari 3" },
    { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 50, ["name"] = "Lumanari 4" },
    { ["object"] = "prop_mem_candle_01", ["price"] = 300, ["name"] = "Lumanari 5" },
    { ["object"] = "p_int_jewel_mirror", ["price"] = 700, ["name"] = "Oglinda" }, 
    { ["object"] = "apa_mp_h_acc_dec_plate_01", ["price"] = 700, ["name"] = "Farfurie Decorativa" }, 
    { ["object"] = "apa_mp_h_acc_vase_01", ["price"] = 700, ["name"] = "Vaza Alb-Negru" },  
    { ["object"] = "v_res_cherubvase", ["price"] = 500, ["name"] = "Vaza Alba" },
    { ["object"] = "ex_mp_h_acc_vase_06", ["price"] = 300, ["name"] = "Vaza Albastra" },
    { ["object"] = "ex_mp_h_acc_vase_02", ["price"] = 300, ["name"] = "Vaza rosie" },
    { ["object"] = "v_res_desktidy", ["price"] = 700, ["name"] = "Rechizite" },  
    { ["object"] = "ex_prop_ashtray_luxe_02", ["price"] = 700, ["name"] = "Scrumiera" },
    { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Scrumiera 2" },  
    { ["object"] = "prop_bong_01", ["price"] = 700, ["name"] = "Bong" },
    { ["object"] = "prop_mr_rasberryclean", ["price"] = 700, ["name"] = "Ursulet de plus" },
    { ["object"] = "p_planning_board_04", ["price"] = 500, ["name"] = "Tabla" },
    { ["object"] = "p_cs_pamphlet_01_s", ["price"] = 700, ["name"] = "Pamflet" },
    { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
    { ["object"] = "prop_dart_bd_cab_01", ["price"] = 500, ["name"] = "Dart 1" },
    { ["object"] = "prop_dart_bd_01", ["price"] = 500, ["name"] = "Dart 2" },
    { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Manechin" },
    { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
    { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ulcior" },
    { ["object"] = "apa_mp_h_acc_rugwools_01", ["price"] = 300, ["name"] = "Covor 1" },
    { ["object"] = "apa_mp_h_acc_rugwoolm_01", ["price"] = 300, ["name"] = "Covor 2" },
    { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 300, ["name"] = "Covor 3" },
    { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 300, ["name"] = "Covor 4" },
    { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 300, ["name"] = "Covor 5" },
    { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 300, ["name"] = "Covor 6" },
    { ["object"] = "ex_office_citymodel_01", ["price"] = 300, ["name"] = "Model Oras" },
    { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["name"] = "Masca" },
    { ["object"] = "hei_prop_hei_bust_01", ["price"] = 300, ["name"] = "Statuie" },
    { ["object"] = "bkr_prop_weed_pallet", ["price"] = 50, ["name"] = "Palete" },
    { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Masina de spalat 1" },
    { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Masina de spalat 2" },
    { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Masina de spalat 3" },
    { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Cos de rufe" },

    { ["object"] = "bkr_prop_moneypack_03a", ["price"] = 50000, ["name"] = "Bani 1" },
    { ["object"] = "bkr_prop_moneypack_02a", ["price"] = 75000, ["name"] = "Bani 2" },
    { ["object"] = "bkr_prop_money_wrapped_01", ["price"] = 10000, ["name"] = "Bani 3" },
    { ["object"] = "bkr_prop_moneypack_01a", ["price"] = 25000, ["name"] = "Bani 4" },
  },
  ['Dulapuri'] = {
    { ["object"] = "prop_devin_box_closed", ["price"] = 500, ["name"] = "Cutie de haine" },
    { ["object"] = "prop_ld_int_safe_01", ["price"] = 500, ["name"] = "Seif 1" },
    { ["object"] = "p_v_43_safe_s", ["price"] = 500, ["name"] = "Seif 2" },
    { ["object"] = "prop_gun_case_02", ["price"] = 500, ["name"] = "Servieta cu arma" },
    { ["object"] = "p_cs_locker_01_s", ["price"] = 500, ["name"] = "Dulap de fier" },
    { ["object"] = "apa_mp_h_str_sideboards_01", ["price"] = 500, ["name"] = "Dulapior"},
    { ["object"] = "prop_champ_box_01", ["price"] = 500, ["name"] = "Cutie de lemn" },
    { ["object"] = "prop_cabinet_02b", ["price"] = 500, ["name"] = "Dulap de acte 1" },
    { ["object"] = "prop_cabinet_01b", ["price"] = 500, ["name"] = "Dulap de acte 2" },
    { ["object"] = "prop_fbibombfile", ["price"] = 500, ["name"] = "Dulap de acte 3" },
    { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 500, ["name"] = "Mobilier" },
    { ["object"] = "prop_rub_cabinet02", ["price"] = 500, ["name"] = "Cabinet 1" },
    { ["object"] = "prop_rub_cabinet01", ["price"] = 500, ["name"] = "Cabinet 2" },
    { ["object"] = "prop_rub_cabinet03", ["price"] = 500, ["name"] = "Cabinet 3" },
    { ["object"] = "apa_mp_h_str_shelffreel_01", ["price"] = 500, ["name"] = "Raft mare 1" },
    { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["name"] = "Raft mare 2" },
    { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 500, ["name"] = "Raft carti" },
    { ["object"] = "hei_heist_str_sideboardl_03", ["price"] = 500, ["name"] = "Dulap bucatarie 1" },
    { ["object"] = "p_new_j_counter_02", ["price"] = 500, ["name"] = "Dulap bucatarie 2" },
  },
  ['Iluminare'] = {
    { ["object"] = "prop_cd_lamp", ["price"] = 100, ["name"] = "Lumini 1" },
    { ["object"] = "hei_prop_hei_bnk_lamp_02", ["price"] = 100, ["name"] = "Lumini 2" },
    { ["object"] = "hei_prop_hei_bnk_lamp_01", ["price"] = 100, ["name"] = "Lumini 3" },
    { ["object"] = "prop_chall_lamp_02", ["price"] = 100, ["name"] = "Lumini 4" },
    { ["object"] = "v_ilev_fh_lampa_on", ["price"] = 100, ["name"] = "Lumini 5" },
    { ["object"] = "prop_construcionlamp_01", ["price"] = 100, ["name"] = "Lumini 6" },
    { ["object"] = "hei_prop_bank_ornatelamp", ["price"] = 100, ["name"] = "Lumini 7" },
    { ["object"] = "prop_kino_light_03", ["price"] = 100, ["name"] = "Lumini 8" },
    { ["object"] = "prop_oldlight_01c", ["price"] = 100, ["name"] = "Lumini 9" },
    { ["object"] = "prop_recycle_light", ["price"] = 100, ["name"] = "Lumini 10" },
    { ["object"] = "prop_studio_light_01", ["price"] = 100, ["name"] = "Lumini 11" },
    { ["object"] = "prop_studio_light_02", ["price"] = 100, ["name"] = "Lumini 12" },
    { ["object"] = "prop_wall_light_02a", ["price"] = 100, ["name"] = "Lumini 13" },
    { ["object"] = "prop_wall_light_03a", ["price"] = 100, ["name"] = "Lumini 14" },
    { ["object"] = "prop_wall_light_04a", ["price"] = 100, ["name"] = "Lumini 15" },
    { ["object"] = "prop_wall_light_05a", ["price"] = 100, ["name"] = "Lumini 16" },
    { ["object"] = "prop_wall_light_05c", ["price"] = 100, ["name"] = "Lumini 17" },
    { ["object"] = "prop_traffic_lightset_01", ["price"] = 100, ["name"] = "Traffic Lights" },
    { ["object"] = "apa_mp_h_lit_floorlamp_01", ["price"] = 100, ["name"] = "Veioza 1" },
    { ["object"] = "apa_mp_h_lit_floorlamp_02", ["price"] = 100, ["name"] = "Veioza 2" },
    { ["object"] = "apa_mp_h_lit_floorlamp_03", ["price"] = 100, ["name"] = "Veioza 3" },
    { ["object"] = "apa_mp_h_lit_floorlamp_04", ["price"] = 100, ["name"] = "Veioza 4" },
    { ["object"] = "apa_mp_h_lit_floorlamp_05", ["price"] = 100, ["name"] = "Veioza 5" },
    { ["object"] = "apa_mp_h_lit_floorlamp_06", ["price"] = 100, ["name"] = "Veioza 6" },
    { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["name"] = "Veioza 7" },
    { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["name"] = "Veioza 8" },
    { ["object"] = "apa_mp_h_lit_floorlamp_17", ["price"] = 100, ["name"] = "Veioza 9" },
    { ["object"] = "hei_heist_lit_floorlamp_03", ["price"] = 100, ["name"] = "Veioza 9" },
    { ["object"] = "hei_heist_lit_floorlamp_04", ["price"] = 100, ["name"] = "Veioza 10" },
    { ["object"] = "hei_heist_lit_floorlamp_05", ["price"] = 100, ["name"] = "Veioza 11" },
    { ["object"] = "hei_heist_lit_floorlamp_02", ["price"] = 100, ["name"] = "Veioza 12" },
    { ["object"] = "hei_heist_lit_floorlamp_01", ["price"] = 100, ["name"] = "Veioza 13" },
    { ["object"] = "apa_mp_h_lit_floorlampnight_05", ["price"] = 100, ["name"] = "Veioza 14" },
    { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["name"] = "Veioza 15" },
    { ["object"] = "apa_mp_h_lit_floorlampnight_14", ["price"] = 100, ["name"] = "Veioza 16" },
    { ["object"] = "apa_mp_h_lit_lamptable_005", ["price"] = 100, ["name"] = "Lampa 1" },
    { ["object"] = "apa_mp_h_lit_lamptable_02", ["price"] = 100, ["name"] = "Lampa 2" },
    { ["object"] = "apa_mp_h_lit_lamptable_09", ["price"] = 100, ["name"] = "Lampa 3" },
    { ["object"] = "apa_mp_h_lit_lamptable_04", ["price"] = 100, ["name"] = "Lampa 4" },
    { ["object"] = "apa_mp_h_lit_lamptable_14", ["price"] = 100, ["name"] = "Lampa 5" },
    { ["object"] = "apa_mp_h_lit_lamptable_17", ["price"] = 100, ["name"] = "Lampa 6" },
    { ["object"] = "apa_mp_h_lit_lamptable_21", ["price"] = 100, ["name"] = "Lampa 7" },
    { ["object"] = "hei_heist_lit_lamptable_02", ["price"] = 100, ["name"] = "Lampa 8" },
    { ["object"] = "hei_heist_lit_lamptable_03", ["price"] = 100, ["name"] = "Lampa 9" },
    { ["object"] = "hei_heist_lit_lamptable_04", ["price"] = 100, ["name"] = "Lampa 10" },
    { ["object"] = "hei_heist_lit_lamptable_05", ["price"] = 100, ["name"] = "Lampa 11" },
    { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["name"] = "Lampa 12" },
    { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 100, ["name"] = "Lampa 13" },
    { ["object"] = "apa_mp_h_lit_lightpendant_01", ["price"] = 100, ["name"] = "Lumina de tavan 1" },
    { ["object"] = "apa_mp_h_lit_lightpendant_05", ["price"] = 100, ["name"] = "Lumina de tavan 2" },
    { ["object"] = "apa_mp_h_lit_lightpendant_05b", ["price"] = 100, ["name"] = "Lumina de tavan 3" },
    { ["object"] = "hei_heist_lit_lightpendant_003", ["price"] = 100, ["name"] = "Lumina de tavan 4" },
    { ["object"] = "hei_heist_lit_lightpendant_01", ["price"] = 100, ["name"] = "Lumina de tavan 5" },
    { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 100, ["name"] = "Lumina de tavan 6" },
  },
  ['Plante'] = {
    { ["object"] = "bkr_prop_weed_01_small_01a", ["price"] = 100, ["name"] = "Planta Marijuana Mica" },
    { ["object"] = "bkr_prop_weed_lrg_01b", ["price"] = 100, ["name"] = "Planta Marijuana Medie" },
    { ["object"] = "prop_weed_01", ["price"] = 100, ["name"] = "Planta Marijuana Mare" },
    { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Brad de craciun" },
    { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Vaza cu flori" },
    { ["object"] = "p_int_jewel_plant_02", ["price"] = 170, ["name"] = "Planta 1" },
    { ["object"] = "p_int_jewel_plant_01", ["price"] = 170, ["name"] = "Planta 2" },
    { ["object"] = "prop_fbibombplant", ["price"] = 170, ["name"] = "Planta 3" },
    { ["object"] = "prop_fib_plant_02", ["price"] = 170, ["name"] = "Planta 4" },
    { ["object"] = "prop_ld_dstplanter_01", ["price"] = 170, ["name"] = "Planta 5" },
    { ["object"] = "prop_ld_planter2b", ["price"] = 170, ["name"] = "Planta 6" },
    { ["object"] = "prop_plant_int_01a", ["price"] = 170, ["name"] = "Planta 7" },
    { ["object"] = "prop_plant_int_01b", ["price"] = 170, ["name"] = "Planta 8" },
    { ["object"] = "prop_plant_int_02a", ["price"] = 170, ["name"] = "Planta 9" },
    { ["object"] = "prop_plant_int_02b", ["price"] = 170, ["name"] = "Planta 10" },
    { ["object"] = "prop_plant_int_03a", ["price"] = 170, ["name"] = "Planta 11" },
    { ["object"] = "prop_plant_int_03b", ["price"] = 170, ["name"] = "Planta 12" },
    { ["object"] = "prop_plant_int_03c", ["price"] = 170, ["name"] = "Planta 13" },
    { ["object"] = "prop_plant_int_04a", ["price"] = 170, ["name"] = "Planta 14" },
    { ["object"] = "prop_plant_int_04b", ["price"] = 170, ["name"] = "Planta 15" },
    { ["object"] = "prop_plant_int_04c", ["price"] = 170, ["name"] = "Planta 16" },
    { ["object"] = "prop_pot_plant_01a", ["price"] = 170, ["name"] = "Planta 17" },
    { ["object"] = "prop_pot_plant_01b", ["price"] = 170, ["name"] = "Planta 18" },
    { ["object"] = "prop_pot_plant_01c", ["price"] = 170, ["name"] = "Planta 19" },
    { ["object"] = "prop_pot_plant_01d", ["price"] = 170, ["name"] = "Planta 20" },
    { ["object"] = "prop_pot_plant_03c", ["price"] = 170, ["name"] = "Planta 21" },
    { ["object"] = "prop_pot_plant_05a", ["price"] = 170, ["name"] = "Planta 22" },
    { ["object"] = "prop_plant_palm_01a", ["price"] = 170, ["name"] = "Planta 23" },
    { ["object"] = "prop_plant_palm_01c", ["price"] = 170, ["name"] = "Planta 24" },
    { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 170, ["name"] = "Planta 25" },
    { ["object"] = "apa_mp_h_acc_plant_tall_01", ["price"] = 170, ["name"] = "Planta 26" },
    { ["object"] = "apa_mp_h_acc_plant_palm_01", ["price"] = 170, ["name"] = "Planta 27" },
    { ["object"] = "prop_fib_plant_01", ["price"] = 170, ["name"] = "Planta 28"},
  },
  ["Bucatarie"] = {
    { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Frigider 1" },
    { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Frigider 2" },
    { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Frigider 3" },
    { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Frigider 4" },
    { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Aragaz" },
    { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Cuptor cu microunde 1" },
    { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Cuptor cu microunde 2" },
    { ["object"] = "prop_micro_04", ["price"] = 500, ["name"] = "Cuptor cu microunde 3" },
    { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Tigaie 1" },
    { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Tigaie 2" },
    { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Tigaie 3" },
    { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Platou de tort" },
    { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Fund" },
    { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Tacamuri" },
    { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pestle" },
    { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "Sul de hartie 1" },
    { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "Sul de hartie 2" },
    { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Oala 1" },
    { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Oala 2" },
    { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Oala 3" },
    { ["object"] = "prop_copper_pan", ["price"] = 500, ["name"] = "Oala 4" },
    { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Ibric" },
    { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Suport de tigai" },
    { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Robot" },
    { ["object"] = "apa_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Masina de cafea" },
    { ["object"] = "hei_heist_kit_bin_01", ["price"] = 500, ["name"] = "Cos de gunoi" },
    { ["object"] = "hei_prop_hei_paper_bag", ["price"] = 500, ["name"] = "Punga de carton" },
    { ["object"] = "apa_mp_h_acc_fruitbowl_01", ["price"] = 500, ["name"] = "Platou cu fructe" },
    { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 500, ["name"] = "Bol cu fructe" },
    { ["object"] = "prop_bar_fruit", ["price"] = 500, ["name"] = "Tava cu fructe" },
    { ["object"] = "prop_bar_lemons", ["price"] = 500, ["name"] = "Farfurie cu lamai" },
    { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Struguri" },
    { ["object"] = "prop_bar_measrjug", ["price"] = 500, ["name"] = "Cana gradata" },
    { ["object"] = "prop_bar_sink_01", ["price"] = 500, ["name"] = "Chiuveta" },
    { ["object"] = "prop_cleaver", ["price"] = 500, ["name"] = "Satar" },
    { ["object"] = "v_ilev_fh_kitchenstool", ["price"] = 500, ["name"] = "Taburete bucatarie" },
    { ["object"] = "prop_trailr_fridge", ["price"] = 500, ["name"] = "Frigider vechi" },
    { ["object"] = "prop_vend_fridge01", ["price"] = 500, ["name"] = "Tolomat de sucuri" },
    { ["object"] = "prop_vend_snak_01", ["price"] = 500, ["name"] = "Tolomat de snacks-uri" },
    { ["object"] = "prop_vend_coffe_01", ["price"] = 500, ["name"] = "Tolomat de cafea" },
    { ["object"] = "prop_vend_soda_01", ["price"] = 500, ["name"] = "Tolomat de Coca Cola" },
    { ["object"] = "prop_vend_soda_02", ["price"] = 500, ["name"] = "Tolomat de Sprite" },
    { ["object"] = "prop_vend_water_01", ["price"] = 500, ["name"] = "Tolomat de Apa" },
    { ["object"] = "prop_watercooler", ["price"] = 500, ["name"] = "Distribuitor de Apa" },
    { ["object"] = "prop_bar_drinkstraws", ["price"] = 500, ["name"] = "Paie" },
    { ["object"] = "prop_toaster_01", ["price"] = 500, ["name"] = "Toaster 1" },
    { ["object"] = "prop_toaster_02", ["price"] = 500, ["name"] = "Toaster 2" },
    { ["object"] = "p_cs_toaster_s", ["price"] = 500, ["name"] = "Toaster 3" },
    { ["object"] = "v_ilev_m_pitcher", ["price"] = 500, ["name"] = "Cana gradata" },
    { ["object"] = "apa_prop_cs_plastic_cup_01", ["price"] = 500, ["name"] = "Pahar reciclabil rosu" },
    { ["object"] = "prop_plate_01", ["price"] = 500, ["name"] = "Farfurii" },
	{ ["object"] = "prop_tall_glass", ["price"] = 100, ["name"] = "Pahar mare" },
    { ["object"] = "prop_mug_01", ["price"] = 500, ["name"] = "Cana 1" },
    { ["object"] = "prop_mug_02", ["price"] = 500, ["name"] = "Cana 2" },
    { ["object"] = "prop_mug_03", ["price"] = 500, ["name"] = "Cana 3" },
    { ["object"] = "prop_mug_04", ["price"] = 500, ["name"] = "Cana 4" },
    { ["object"] = "prop_mug_06", ["price"] = 500, ["name"] = "Cana 5" },
    { ["object"] = "prop_foodprocess_01", ["price"] = 500, ["name"] = "Robot de bucatarie" },
  },
  ["Baie"] = {
    { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Toaleta 1" },
    { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Toaleta 2" },
    { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Toaleta 3" },
    { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Chiuveta 1" },
    { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Chiuveta 2" },
    { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Chiuveta 3" },
    { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Chiuveta 4" },
    { ["object"] = "prop_sink_03", ["price"] = 100, ["name"] = "Chiuveta 5" },
    { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Distribuitor de sapun" },
    { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Suport de dus" },
    { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Uscator de maini 1" },
    { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Uscator de maini 2" },
    { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Sina de prosop 1" },
    { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Sina de prosop 2" },
    { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Prosop 1" },
    { ["object"] = "prop_shower_towel", ["price"] = 100, ["name"] = "Prosop 2" },
    { ["object"] = "p_shower_towel_s", ["price"] = 100, ["name"] = "Prosop 3" },
    { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 100, ["name"] = "Bathtub" },
    { ["object"] = "prop_beach_lotion_01", ["price"] = 100, ["name"] = "Lotiune 1" },
    { ["object"] = "prop_beach_lotion_02", ["price"] = 100, ["name"] = "Lotiune 2" },
    { ["object"] = "prop_beach_lotion_03", ["price"] = 100, ["name"] = "Lotiune 3" },
    { ["object"] = "prop_clippers_01", ["price"] = 100, ["name"] = "Clippers" },
    { ["object"] = "prop_toilet_brush_01", ["price"] = 100, ["name"] = "Perie de WC" },
    { ["object"] = "prop_toilet_roll_01", ["price"] = 100, ["name"] = "Hartie Igienica 1" },
    { ["object"] = "prop_toilet_roll_02", ["price"] = 100, ["name"] = "Hartie Igienica 2" },
    { ["object"] = "prop_toilet_roll_05", ["price"] = 100, ["name"] = "Hartie Igienica 3" },
    { ["object"] = "prop_toilet_shamp_01", ["price"] = 100, ["name"] = "Sampon" },
    { ["object"] = "prop_toilet_shamp_02", ["price"] = 100, ["name"] = "Sampon" },
    { ["object"] = "prop_toilet_soap_01", ["price"] = 100, ["name"] = "Sapun 1" },
    { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["name"] = "Sapun 2" },
    { ["object"] = "prop_toilet_soap_03", ["price"] = 100, ["name"] = "Sapun 3" },
    { ["object"] = "prop_toilet_soap_04", ["price"] = 100, ["name"] = "Sapun 4" },
    { ["object"] = "prop_toothbrush_01", ["price"] = 100, ["name"] = "Periuta de dinti" },
    { ["object"] = "prop_toothpaste_01", ["price"] = 100, ["name"] = "Pasta de dinti" },
    { ["object"] = "prop_disp_razor_01", ["price"] = 100, ["name"] = "Lama de ras" },
  },
  ['Mancare si bauturi'] = {
	{ ["object"] = "p_ing_coffeecup_02", ["price"] = 100, ["name"] = "Cafea" },
	-- alcoale
	{ ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Bax de bere 1" },
	{ ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Bax de bere 2" },
	{ ["object"] = "beerrow_world", ["price"] = 100, ["name"] = "Sticla de bere 1" },
	{ ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Sticla de bere 2" },
	{ ["object"] = "prop_beer_blr", ["price"] = 100, ["name"] = "Sticla de bere 3" },
	{ ["object"] = "prop_beer_logger", ["price"] = 100, ["name"] = "Sticla de bere 4" },
	{ ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Sticla de bere 5" },
	{ ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Sticla de bere 6" },
	{ ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Sticla de Whiskey" },
	{ ["object"] = "prop_wine_red", ["price"] = 100, ["name"] = "Sticla de Vin Rosu" },
	{ ["object"] = "prop_wine_rose", ["price"] = 100, ["name"] = "Sticla de Vin Rose" },
	{ ["object"] = "prop_wine_white", ["price"] = 100, ["name"] = "Sticla de Vin Alb" },
	{ ["object"] = "prop_tequila_bottle", ["price"] = 100, ["name"] = "Sticla de Tequila" },
	{ ["object"] = "prop_whiskey_bottle", ["price"] = 100, ["name"] = "Sticla de Whiskey" },
	{ ["object"] = "lts_prop_wine_glass_s2", ["price"] = 100, ["name"] = "Pahar cu vin alb" },
	{ ["object"] = "p_wine_glass_s", ["price"] = 100, ["name"] = "Pahar cu vin rosu" },
	{ ["object"] = "hei_p_hei_champ_flute_s", ["price"] = 100, ["name"] = "Pahar cu sampanie" },
	{ ["object"] = "p_cs_shot_glass_2_s", ["price"] = 100, ["name"] = "Pahar de shot" },
	{ ["object"] = "prop_cherenkov_01", ["price"] = 100, ["name"] = "Vodka 1" },
	{ ["object"] = "prop_cherenkov_02", ["price"] = 100, ["name"] = "Vodka 2" },
	{ ["object"] = "prop_cava", ["price"] = 100, ["name"] = "Sticla de vin" },
	{ ["object"] = "prop_cocktail", ["price"] = 100, ["name"] = "Cocktail" },
	{ ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 OZ" },
	{ ["object"] = "prop_tequila", ["price"] = 100, ["name"] = "Tequila" },
	{ ["object"] = "prop_tequsunrise", ["price"] = 100, ["name"] = "Tequila 2" },
	{ ["object"] = "prop_pinacolada", ["price"] = 100, ["name"] = "Pina Colada" },
	{ ["object"] = "prop_drink_champ", ["price"] = 100, ["name"] = "Pahar de Sampanie" },
	{ ["object"] = "prop_drink_whtwine", ["price"] = 100, ["name"] = "Pahar de Vin Alb" },
	{ ["object"] = "prop_drink_whisky", ["price"] = 100, ["name"] = "Pahar cu Whiskey" },
	{ ["object"] = "ex_office_swag_booze_cigs2", ["price"] = 100, ["name"] = "Vodka si Tigari" },
	{ ["object"] = "winerow", ["price"] = 100, ["name"] = "Sticle de Vin" },
	{ ["object"] = "vodkarow", ["price"] = 100, ["name"] = "Sticle de Vodka" },
	-- sucuri si cafea
	{ ["object"] = "ng_proc_sodacan_01a", ["price"] = 100, ["name"] = "Doza de suc 1" },
	{ ["object"] = "ng_proc_sodacan_01b", ["price"] = 100, ["name"] = "Doza de suc 2" },
	{ ["object"] = "prop_orang_can_01", ["price"] = 100, ["name"] = "Doza de suc 3" },
	{ ["object"] = "ng_proc_sodabot_01a", ["price"] = 100, ["name"] = "Soda Bottle" },
	{ ["object"] = "p_w_grass_gls_s", ["price"] = 100, ["name"] = "Suc de mere" },
	-- mancare
	{ ["object"] = "ng_proc_food_bag01a", ["price"] = 100, ["name"] = "Burger Shot" },
	{ ["object"] = "prop_food_bs_burg1", ["price"] = 100, ["name"] = "Burger 1" },
	{ ["object"] = "prop_food_bs_burg3", ["price"] = 100, ["name"] = "Burger 2" },
	{ ["object"] = "prop_food_bs_chips", ["price"] = 100, ["name"] = "Chips-uri" },
	{ ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Alune" },
	{ ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Bol cu chips-uri" },
	{ ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Dulciuri" },
	{ ["object"] = "prop_cs_burger_01", ["price"] = 100, ["name"] = "Burger" },
	{ ["object"] = "prop_peanut_bowl_01", ["price"] = 300, ["name"] = "Bol cu alune" },
	{ ["object"] = "prop_fruit_stand_03", ["price"] = 300, ["name"] = "Cutii cu pepeni" },
	{ ["object"] = "prop_fruit_stand_02", ["price"] = 300, ["name"] = "Cutii cu portocale" },
	{ ["object"] = "prop_turkey_leg_01", ["price"] = 100, ["name"] = "Pulpa de Curcan" },
	{ ["object"] = "prop_veg_crop_03_pump", ["price"] = 100, ["name"] = "Dovleac" },
	{ ["object"] = "prop_pineapple", ["price"] = 100, ["name"] = "Ananas" },
	{ ["object"] = "prop_pizza_box_01", ["price"] = 100, ["name"] = "Cutie de Pizza 1" },
	{ ["object"] = "prop_pizza_box_02", ["price"] = 100, ["name"] = "Cutie de Pizza 2" },
	{ ["object"] = "prop_pizza_box_03", ["price"] = 100, ["name"] = "Cutie de Pizza 3" },
	{ ["object"] = "prop_cs_plate_01", ["price"] = 100, ["name"] = "Farfurie cu mancare" },
	{ ["object"] = "prop_cs_crisps_01", ["price"] = 100, ["name"] = "Punga de chipsuri" },
	{ ["object"] = "prop_donut_01", ["price"] = 100, ["name"] = "Gogoasa" },
  },
  ["Bijuterii"] = {
    { ["object"] = "prop_jewel_03b", ["price"] = 7000, ["name"] = "Jewel 1" },
    { ["object"] = "prop_jewel_04b", ["price"] = 7000, ["name"] = "Jewel 2" },
    { ["object"] = "prop_jewel_02b", ["price"] = 7000, ["name"] = "Jewel 3" },
    { ["object"] = "prop_jewel_pickup_new_01", ["price"] = 7000, ["name"] = "Jewel 4" },
    { ["object"] = "prop_jewel_02a", ["price"] = 7000, ["name"] = "Jewel 5" },
    { ["object"] = "prop_jewel_02c", ["price"] = 7000, ["name"] = "Jewel 6" },
    { ["object"] = "prop_jewel_03a", ["price"] = 7000, ["name"] = "Jewel 7" },
    { ["object"] = "prop_jewel_04a", ["price"] = 7000, ["name"] = "Jewel 8" },
    { ["object"] = "p_watch_01", ["price"] = 5000, ["name"] = "Watch 1" },
    { ["object"] = "p_watch_02", ["price"] = 5000, ["name"] = "Watch 2" },
    { ["object"] = "p_watch_03", ["price"] = 5000, ["name"] = "Watch 3" },
    { ["object"] = "p_watch_04", ["price"] = 5000, ["name"] = "Watch 4" },
    { ["object"] = "p_watch_05", ["price"] = 5000, ["name"] = "Watch 5" },
    { ["object"] = "p_watch_06", ["price"] = 5000, ["name"] = "Watch 6" },
    { ["object"] = "prop_cash_case_02", ["price"] = 50000, ["name"] = "Cash Case" },
    { ["object"] = "prop_cash_crate_01", ["price"] = 40000, ["name"] = "Cash Crate" },
    { ["object"] = "hei_prop_cash_crate_half_full", ["price"] = 5000, ["name"] = "Cash Crate 2" },
    { ["object"] = "prop_anim_cash_note_b", ["price"] = 5000, ["name"] = "Cash Note" },
    { ["object"] = "prop_anim_cash_pile_01", ["price"] = 5000, ["name"] = "Cash Pile" },
    { ["object"] = "prop_cash_trolly", ["price"] = 5000, ["name"] = "Cash Trolly" },
    { ["object"] = "prop_poly_bag_money", ["price"] = 5000, ["name"] = "Money Bag" },
    { ["object"] = "prop_gold_trolly_full", ["price"] = 5000, ["name"] = "Gold Trolly" },
    { ["object"] = "prop_gold_trolly", ["price"] = 5000, ["name"] = "Gold Trolly 2" },
    { ["object"] = "prop_gold_bar", ["price"] = 5000, ["name"] = "Gold Bar" },
    { ["object"] = "prop_large_gold", ["price"] = 5000, ["name"] = "Large Gold" },
    { ["object"] = "p_large_gold_s", ["price"] = 5000, ["name"] = "Large Gold 2" },
    { ["object"] = "prop_ld_gold_chest", ["price"] = 5000, ["name"] = "Gold Chest" },
    { ["object"] = "prop_idol_case_01", ["price"] = 5000, ["name"] = "Idol Case" },
    { ["object"] = "prop_j_disptray_01", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_01b", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_02", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_03", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_04", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_04b", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_05", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_05b", ["price"] = 5000, ["name"] = "Display Tray" },
    { ["object"] = "v_res_jewelbox", ["price"] = 5000, ["name"] = "Jewel Box" },
    { ["object"] = "prop_peyote_gold_01", ["price"] = 5000, ["name"] = "Peyote Gold" },
    { ["object"] = "prop_cs_cash_note_01", ["price"] = 5000, ["name"] = "Cash Note 2" },

  },
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end